# Generated by Django 4.0.5 on 2022-06-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ingredients_item_name_alter_inventory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='order_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
